spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: Ehowtan2005



mybatis:
  mapper-locations: classpath:mapper/*.xml
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

